### ISSUE TITLE
Crashs with Optifine

### ISSUE THREAD

**Issue by 2mal3** [enjarai/moderate-loading-screen#6]
When starting together with Optifine Minecraft always crashes.
Everything else should be in the log.

[latest.log](https://github.com/enjarai/moderate-loading-screen/files/7890228/latest.log)

**Comment by enjarai** [comment]
This appears to be a problem with Cloth API, which my mod makes use of: https://github.com/Chocohead/OptiFabric/issues/577

Optifine is generally very hard for mod devs to support, because of the way its coded. For better compatibility i'd suggest looking at fabric alternatives to optifine features: https://lambdaurora.dev/optifine_alternatives/
